convert -resize 16x16 img/tray-icon.png img/IconTemplate.png
convert -resize 20x20 img/tray-icon.png img/IconTemplate@1.25x.png
convert -resize 21.22x21.22 img/tray-icon.png img/IconTemplate@1.33x.png
convert -resize 22.2x22.4 img/tray-icon.png img/IconTemplate@1.4x.png
convert -resize 24x24 img/tray-icon.png img/IconTemplate@1.5x.png
convert -resize 28.8x28.8 img/tray-icon.png img/IconTemplate@1.8x.png
convert -resize 32x32 img/tray-icon.png img/IconTemplate@2x.png
convert -resize 40x40 img/tray-icon.png img/IconTemplate@2.5x.png
convert -resize 48x48 img/tray-icon.png img/IconTemplate@3x.png
convert -resize 64x64 img/tray-icon.png img/IconTemplate@4x.png
convert -resize 80x80 img/tray-icon.png img/IconTemplate@5x.png
